//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSProject.Areas.Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMSEntities : DbContext
    {
        public CMSEntities()
            : base("name=CMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Beneficiary> Beneficiaries { get; set; }
        public DbSet<BeneficiaryClass> BeneficiaryClasses { get; set; }
        public DbSet<Community> Communities { get; set; }
        public DbSet<Municipality> Municipalities { get; set; }
        public DbSet<Organization> Organizations { get; set; }
        public DbSet<ProductiveSector> ProductiveSectors { get; set; }
        public DbSet<Profile> Profiles { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<SessionAttachment> SessionAttachments { get; set; }
        public DbSet<SessionParticipant> SessionParticipants { get; set; }
        public DbSet<Session> Sessions { get; set; }
        public DbSet<SessionStatus> SessionStatuses { get; set; }
        public DbSet<Teacher> Teachers { get; set; }
        public DbSet<TypeOfBeneficiary> TypeOfBeneficiaries { get; set; }
    }
}
