//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSProject.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel;
    
    public partial class Community
    {
        public Community()
        {
            this.Beneficiaries = new HashSet<Beneficiary>();
            this.Organizations = new HashSet<Organization>();
        }
    
        public int CommunityID { get; set; }
        [DisplayName("Community")]
        public string Name { get; set; }
        public Nullable<int> MunicipalID { get; set; }
    
        public virtual ICollection<Beneficiary> Beneficiaries { get; set; }
        public virtual Municipality Municipality { get; set; }
        public virtual ICollection<Organization> Organizations { get; set; }
    }
}
