//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSProject.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.TypeOfBeneficiaries = new HashSet<TypeOfBeneficiary>();
            this.BeneficiaryClasses = new HashSet<BeneficiaryClass>();
            this.TypeOfBeneficiaries1 = new HashSet<TypeOfBeneficiary>();
        }
    
        public int ProfileID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<TypeOfBeneficiary> TypeOfBeneficiaries { get; set; }
        public virtual ICollection<BeneficiaryClass> BeneficiaryClasses { get; set; }
        public virtual ICollection<TypeOfBeneficiary> TypeOfBeneficiaries1 { get; set; }
    }
}
