//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSProject.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public Session()
        {
            this.SessionAttachments = new HashSet<SessionAttachment>();
            this.SessionParticipants = new HashSet<SessionParticipant>();
        }
    
        public int SessionID { get; set; }
        public int BeneficiaryClassID { get; set; }
        public System.DateTime InitialDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Venue { get; set; }
        public string Place { get; set; }
        public int TeacherID { get; set; }
        public int ProjectID { get; set; }
        public int SessionStatusID { get; set; }
    
        public virtual BeneficiaryClass BeneficiaryClass { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<SessionAttachment> SessionAttachments { get; set; }
        public virtual ICollection<SessionParticipant> SessionParticipants { get; set; }
        public virtual SessionStatus SessionStatus { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
