//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSProject.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionParticipant
    {
        public int ID { get; set; }
        public int SessionID { get; set; }
        public int BeneficiaryID { get; set; }
        public bool Attended { get; set; }
        public bool Completed { get; set; }
    
        public virtual Beneficiary Beneficiary { get; set; }
        public virtual Session Session { get; set; }
    }
}
