//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSProject.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.Sessions = new HashSet<Session>();
        }
        public int TeacherID { get; set; }
        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Photo { get; set; }
        [Range(11,11,ErrorMessage="Please Enter 11 digit card number")]
        public string IdentificationCardNumber { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        [EmailAddress(ErrorMessage = "Email is required")]
        public string Email { get; set; }
    
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
