//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSProject.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeOfBeneficiary
    {
        public TypeOfBeneficiary()
        {
            this.Beneficiaries = new HashSet<Beneficiary>();
            this.Profiles = new HashSet<Profile>();
            this.Profiles1 = new HashSet<Profile>();
        }
    
        public int TypeOfBeneficiaryID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Beneficiary> Beneficiaries { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
        public virtual ICollection<Profile> Profiles1 { get; set; }
    }
}
